# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Me2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Me2
  pod 'Cartography'
  pod 'IQKeyboardManagerSwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Cosmos', '~> 19.0'
  pod 'ImageSlideshow', '~> 1.8'
  pod 'ImageSlideshow/Kingfisher'
  pod 'KKPinCodeTextField'
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'GoogleSignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'RangeSeekSlider'
  pod 'ShimmerSwift'
  pod 'Starscream', '~> 3.0.2'
  pod 'NVActivityIndicatorView'
  pod 'OneSignal', '>= 2.6.2', '< 3.0'
end

target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
